export const ACTION_TYPES = {
  ALL_MOVIES: {
    REQUESTING: 'ALL_MOVIES_REQUESTING',
    SUCCESS: 'ALL_MOVIES_SUCCESS',
    ERROR: 'ALL_MOVIES_ERROR'
  },

  ADD_TO_MY_LIST: {
    REQUESTING: 'ADD_TO_MY_LIST_REQUESTING',
    SUCCESS: 'ADD_TO_MY_LIST_SUCCESS',
    ERROR: 'ADD_TO_MY_LIST_ERROR',
    DELETE: 'ADD_TO_MY_LIST_DELETE'
  },

  MOVIE_PAGE: {
    REQUESTING: 'MOVIE_PAGE_REQUESTING',
    SUCCESS: 'MOVIE_PAGE_SUCCESS',
    ERROR: 'MOVIE_PAGE_ERROR'
  },

};;
// USER: "USER",
// ADD_TO_MY_LIST: "ADD_TO_MY_LIST",
// MOVIE_PAGE: "MOVIE_PAGE",
// REMOVE_MOVIE_FROM_LIST: 'REMOVE_MOVIE_FROM_LIST'