export const ACTION_TYPES = {

  ADD_TO_MY_LIST: {
    REQUESTING: 'ADD_TO_MY_LIST_REQUESTING',
    SUCCESS: 'ADD_TO_MY_LIST_SUCCESS',
    ERROR: 'ADD_TO_MY_LIST_ERROR',
    DELETE: 'ADD_TO_MY_LIST_DELETE'
  },

  MOVIE_PAGE: {
    REQUESTING: 'MOVIE_PAGE_REQUESTING',
    SUCCESS: 'MOVIE_PAGE_SUCCESS',
    ERROR: 'MOVIE_PAGE_ERROR'
  },

};;